### ISSUE TITLE
After uploading via any asset driver, there's a type error at generator.next().

### ISSUE THREAD

**Issue by DaftVadeR** [burdy-io/burdy#16]
Hi there,

I apologise if I'm being daft or missing something, but I can't seem to get uploads to work. Whenever I try, I get the following error. It happens for both WYSIWYG uploads and image field uploads. 

I've not added any custom hooks or anything yet, it's entirely a fresh install (npx create-burdy-app) outside of setting the config vars and initialising the DB (postgres) and adding two new content types.

I'm running on Windows 10, Node 14.17.0, NPM 6.14.13, Burdy 1.0.5.

Using both 'fs' and 'aws_s3' as the driver.

![Capture](https://user-images.githubusercontent.com/492996/135084294-0928a2a6-c2f9-4688-ad82-9e2031e23693.PNG)

TypeError: Cannot read property 'split' of undefined
    at C:\Users\daft\react-dev\burdy-test\burdy\.dev-build\main.js:1204:18
    at Generator.next (<anonymous>)
    at C:\Users\daft\react-dev\burdy-test\burdy\.dev-build\main.js:1029:71
    at new Promise (<anonymous>)
    at __webpack_modules__../node_modules/burdy/src/server/controllers/asset.controller.js.__awaiter (C:\Users\daft\react-dev\burdy-test\burdy\.dev-build\main.js:1025:12)
    at C:\Users\daft\react-dev\burdy-test\burdy\.dev-build\main.js:1195:55
    at EntityManager.<anonymous> (C:\Users\daft\react-dev\burdy-test\node_modules\typeorm\entity-manager\EntityManager.js:87:50)
    at step (C:\Users\daft\react-dev\burdy-test\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\daft\react-dev\burdy-test\node_modules\tslib\tslib.js:124:57)
    at fulfilled (C:\Users\daft\react-dev\burdy-test\node_modules\tslib\tslib.js:114:62)

Is there something I missed in the installation process? Maybe to allow for asset uploads? Thanks in advance 🙏

**Comment by sandra-burdy** [comment]
Thank you, we will take a look at this issue. Will keep you posted

**Comment by sandra-burdy** [comment]
This error is caused by param name not being provided to the burdy while uploading file, can you maybe provide us with browser that you are using?

**Comment by DaftVadeR** [comment]
I'm using Chrome 94.0.4606.61. 

The posted fields to /api/assets were:

mimeType: image/jpeg
duplicateName: true
file: (binary)

Thanks for your help!

**Comment by sandra-burdy** [comment]
Thank you, we believe we have found an issue and will release an update / new version later today. We will keep you posted.

**Comment by stefan-burdy** [comment]
Hi @DaftVadeR. the linked pull request should resolve the. We will do couple of more checks before releasing a new patch version.

Thank you for the submission!

**Comment by DaftVadeR** [comment]
Thanks for your help - I'll test it out tomorrow morning! Cheers 🕺
