### ISSUE TITLE
custom-editor-field hook not working as expected

### ISSUE THREAD

**Issue by manzsolutions-asc** [burdy-io/burdy#61]
We are testing the headless cms to use it in one of our projects and tried to extend the editor fields by using this documentation.
https://burdy.io/docs/custom-editor-field

At testing it we found out that the reference of the hook in the dynamic-field logic is using the name instead of, as we expected the type, of the custom editor field.
If this reference is intended there would be a problem if the custom editor field would have different names at different cms content types.

**Comment by sandra-burdy** [comment]
Resolved, will be released with burdy 2.0.11

**Comment by sandra-burdy** [comment]
@manzsolutions-asc we have released burdy 2.0.11 with the fixes you have submitted
