### ISSUE TITLE
Publishing post does not automatically save made changes

### ISSUE THREAD

**Issue by Polynook** [burdy-io/burdy#75]
Editing example blog post (_npx create-burdy-app my-blog -t next-blog_) title or content and pressing "Publish" shows "Post(s) published" message, but made changes are not reflected in the webpage under _localhost:4000_. If "Save" is pressed after or before "Publish", made changes are displayed correctly.

I assume this is because pressing "Publish" does not trigger "Save" functionality and is not limited to title or content fields only. I haven't tested under other circumstances though. Not sure if it is intended behavior or not. I was expecting the changes to have been saved automatically when publishing a post.

Here's a short recording depicting the issue.

https://user-images.githubusercontent.com/71569839/148589593-9612c137-93b8-47f3-95e2-d35f6c74d347.mp4

**Comment by sandra-burdy** [comment]
Hi, thank you for the feedback, we have separated save and publish functionality.
It makes sense to publish it with latest updates so ill get back to you on this one as soon as we agree internally how to handle it

**Comment by sandra-burdy** [comment]
Planned, ill work on this one just as soon as I finish a few tasks.

ETA is next Monday!

**Comment by sandra-burdy** [comment]
We are solving one more issue with the editor and will include this enhancement together with that fix

**Comment by sandra-burdy** [comment]
Released in version 2.1.2
