### ISSUE TITLE
Extra file driver registration

### ISSUE THREAD

**Issue by bombozama** [burdy-io/burdy#79]
Hi guys. Love the project.

I see that you currently only support AWS storage and filesystem. Would you guys be open to adding a layer of registration for new drivers, so that extensibility is not limited to content but also to "plugins" (taking the inspiration from Wordpress). In particular, I'm looking to add a multer driver for Google Cloud Storage.

Any thoughts or plans on this?

Cheers.

**Comment by stefan-burdy** [comment]
Hi @bombozama, thanks for using Burdy!

This is planned as Azure Blob has been requested and has sparked interest with some enterprises. We plan to have an investigation, and our plan is to deliver the easy extensibility to file drivers (via hooks) + provide out-of-box support for commonly used ones (Azure Blob and Google Cloud Storage).

Cheers.

**Comment by bombozama** [comment]
I'm attempting to write the GCS driver in my forked burdy. If I get it to work, I'll PR it so that it could be an option for other users as well. Fingers crossed.

**Comment by sandra-burdy** [comment]
Thank you! Please note you will need to either create or install express multer for the google cloud
