### ISSUE TITLE
Dependency path-to-regexp causing preview not working

### ISSUE THREAD

**Issue by grzegorzbialy** [burdy-io/burdy#97]
Hi,

I've tried to turn on preview mode as described in docs and it didn't work so I was trying to reverse the way it is set up and came along to wrong dependency version installed. The error is in the testPaths function in src/admin/helpers/utility.ts and it says match is not a function. 
So, I checked node_modules for path-to-regexp and it is indeed some other (older, I think) code. I've installed 6.2.0 using npm i -S path-to-regexp and preview mode is now working.
I was installing burdy using create-burdy-app so I think there seems to be a bug somewhere in package.json. Sadly, cannot find it - the peerDependency in burdy's package.json is correct 6.2.0.
Will try to investigate.

**Comment by grzegorzbialy** [comment]
It seems that this dependency is not listed in package.json so burdy doesn't build on it's own. Created PR #98 for this.

**Comment by ivan-burdy** [comment]
Thank you @grzegorzbialy I have merged the PR, will do the release later today or tomorrow.

Our team is quite busy getting Burdy Cloud up and running and it will probably take us up to two months, delays on open source version are expected
